collections:
  jobs:
    output: false
  team:
    output: false
  portfolio:
    output: true
    permalink: /test/:path/

defaults:
  - scope:
      type: team
    values:
      order: 100
  - scope:
      type: portfolio
    values:
      order: 100
      style: portfolio
