collections:
  alumni:
    output: false
  jobs:
    output: false
  pages:
    output: true
    permalink: /:path/
  team:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      type: alumni
    values:
      order: 100
  - scope:
      type: jobs
    values:
      visible: true
  - scope:
      type: portfolio
    values:
      order: 100
      style: portfolio
      visible: true
  - scope:
      type: team
    values:
      order: 100
      visible: true
